package com.shatteredpixel.shatteredpixeldungeon.events.processor;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
/*
  Tool used to auto generates target class
 */
public class EventSubscriberIndexGenerator {
    public static void generate(Map<String, List<SubscriberInfo>> subscribers, Filer filer) throws IOException {
        MethodSpec.Builder registerMethod = MethodSpec.methodBuilder("registerAll")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(void.class)
            .addStatement("// Auto-generated event subscriber index")
            .addStatement("// Generated by EventSubscriberProcessor at compile time");

        Map<String, List<SubscriberInfo>> byClass = groupByClass(subscribers);

        for (Map.Entry<String, List<SubscriberInfo>> classEntry : byClass.entrySet()) {
            String className = classEntry.getKey();
            List<SubscriberInfo> methods = classEntry.getValue();

            registerMethod.addCode("\n// $L subscriber methods\n", className);

            for (SubscriberInfo info : methods) {
                registerMethod.addStatement(
                    "EventManager.registerSubscriber($T.class, $T.class, $S, $L)",
                    ClassName.bestGuess(info.eventTypeName),
                    ClassName.bestGuess(info.className),
                    info.methodName,
                    info.priority
                );
            }
        }

        TypeSpec indexClass = TypeSpec.classBuilder("EventSubscriberIndex")
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Auto-generated event subscriber index class.\n")
            .addJavadoc("Do not modify this file manually - it is regenerated at compile time.\n")
            .addMethod(registerMethod.build())
            .build();

        JavaFile.builder("com.shatteredpixel.shatteredpixeldungeon.events", indexClass)
            .build()
            .writeTo(filer);
    }

    private static Map<String, List<SubscriberInfo>> groupByClass(Map<String, List<SubscriberInfo>> subscribers) {
        Map<String, List<SubscriberInfo>> byClass = new HashMap<>();

        for (List<SubscriberInfo> subscriberList : subscribers.values()) {
            for (SubscriberInfo info : subscriberList) {
                byClass.computeIfAbsent(info.className, k -> new ArrayList<>()).add(info);
            }
        }

        // Sort methods by priority (high priority first)
        for (List<SubscriberInfo> methods : byClass.values()) {
            methods.sort((a, b) -> Integer.compare(b.priority, a.priority));
        }

        return byClass;
    }
}